services:
  - type: web
    name: crop-disease-detection
    env: python
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "bash build.sh"
    startCommand: "gunicorn run:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PLANT_ID_API_KEY
        sync: false
